[package]
name = "Gush"
version = "0.1.0"
authors = ["Justin Hurst <JryanhHurst@gmail.com>"]

[lib]
name = "gush"
path = "src/lib.rs"

[dependencies]
gfx = "0.16.0"
gfx_device_gl = "0.14.4"
gfx_window_glutin = "0.17.0"

glutin = "0.9.2"
